---
- name: Template config file
  template:
    src: config.py.j2
    dest: "{{ fts_ui_install_path }}/config.py"
    owner: root
    group: root
    mode: 0644

- name: Template unit file
  template:
    src: fts-ui.service.j2
    dest: "{{ unit_files_location }}/{{ fts_ui_service_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "{{ fts_ui_install_path }}/run.py"

- name: Enable service
  service:
    name: "{{ fts_ui_service_name }}"
    enabled: "{{ fts_ui_enabled }}"
    use: systemd
  register: enable_fts_ui
  retries: 5
  until: enable_fts_ui is success

- name: Set service state
  service:
    name: "{{ fts_ui_service_name }}"
    state: "{{ fts_ui_state }}"
    use: systemd
  register: set_fts_ui_state
  retries: 5
  until: set_fts_ui_state is success
