---
- name: Print IPv4 information
  debug:
    msg: "Using: {{ fts_ui_ip_address }} for {{ role_name }}"

- name: Update FreeTAKServer IPv4 values in config.py
  replace:
    path: "{{ fts_ui_install_path }}/config.py"
    regexp: '127.0.0.1'
    replace: "{{ fts_ip_address }}"

- name: Update webmap IPv4 value in config.py
  replace:
    path: "{{ fts_ui_install_path }}/config.py"
    regexp: 'WEBMAPIP = "127.0.0.1"'
    replace: "WEBMAPIP = \"{{ webmap_ip_address }}\""

- name: Template fts-ui.service unit file
  template:
    src: fts-ui.service.j2
    dest: "{{ unit_files_location }}/{{ fts_ui_service_name }}.service"
    mode: 0644
  notify:
    - enable freetakserver_ui
    - set freetakserver_ui state
