---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "roles/freetakserver_ui/vars/{{ ansible_distribution }}.yml"

- name: Set up FreeTAKServer-UI
  include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}.yml"
    - "roles/freetakserver_ui/tasks/setup-{{ ansible_distribution }}.yml"
  tags: install_fts_ui

- name: Configure FreeTAKServer-UI
  include_tasks: "{{ item }}"
  with_first_found:
    - "configure-{{ ansible_distribution }}.yml"
    - "roles/freetakserver_ui/tasks/configure-{{ ansible_distribution }}.yml"
  tags: configure_fts_ui
