---
- shell: echo $CONDA_DEFAULT_ENV
  register: result

- debug:
    msg: result.stdout_lines

- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers to print at the end
  shell: ":"
  notify:
    - print fts_ui url
    - print fts_ui credentials
