---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Get public IPv4
  ipify_facts:
    api_url: http://api.example.com/ipify
    timeout: 300

- name: Set public IPv4
  set_fact:
    fts_ui_ipv4: "{{ ipify_public_ip }}"

- name: Print IPv4
  debug:
    msg: "fts_ui_ipv4 = {{ fts_ui_ipv4 }}"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers to print at the end
  shell: ":"
  notify:
    - print fts_ui url
    - print fts_ui credentials
