---
- name: Install apt packages
  apt:
    name: "{{ fts_ui_apt_packages }}"

- name: "Install {{ fts_ui_pip_package_name }}"
  shell: "conda run -n {{ VENV_NAME }} pip ininstall -y {{ fts_ui_pip_package_name }}"
