---
- name: Check if FreeTAKServer-UI is installed
  shell: >
        set -o pipefail &&
        {{ pip3 }} list |
        grep FreeTAKServer-UI
  args:
    warn: false
    executable: /bin/bash
  register: result
  changed_when: false
  ignore_errors: true

- name: Install FreeTAKServer-UI
  block:

    - name: "Install {{ fts_ui_pip_package_name }}"
      pip:
        name: "{{ fts_ui_pip_package_name }}"
        executable: "pip{{ python3_version }}"

    - name: Configure FreeTAKServer-UI
      include_tasks: "configure-{{ ansible_distribution }}.yml"

  when: (result.stdout | length == 0)
