all:
  vars:
    app_server:
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: C:\Users\natha\Documents\Certs\ssh certs\DO\digitalocean.pem
      add_ubuntu_interface: true
      app_server_gateway: 159.89.115.27

  children:
    freetakservers:
      hosts:
        159.89.115.27:
          ansible_connection: ssh
          ansible_user: root
          ansible_become: true
          ansible_ssh_private_key_file: /mnt/c/Users/natha/Documents/Certs/ssh certs/DO/digitalocean-private.pem
          add_ubuntu_interface: true