---
# Example hosts.yml
all:
  hosts:
    freetakserver:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

    webmapserver:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

    videoserver:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
 
    noderedserver:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
