---
all:
  hosts:
    freetakserver:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      add_ubuntu_interface: true

    webmap:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      add_ubuntu_interface: true

    videoserver:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      add_ubuntu_interface: true

    noderedserver:
      ansible_host: localhost
      ansible_connection: ssh
      ansible_user: root
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      add_ubuntu_interface: true
