---
# Example hosts.yml
all:
  children:
    freetakservers:
      hosts:
        freetakserver:
          ansible_connection: local
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    webmapservers:
      hosts:
        webmapserver:
          ansble_connection: local
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    videoservers:
      hosts:
        videoserver:
          ansble_connection: local
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    noderedservers:
      hosts:
        noderedserver:
          ansble_connection: local
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    ungrouped: {}
