---
fts_config_path: /opt/FTSConfig.yaml

fts_db_path: /opt/FreeTAKServer.db

my_sitepackages: "{{ CONDA_PREFIX }}/lib/python3.8/site-packages"

fts_install_path: "{{ my_sitepackages }}/FreeTAKServer"

fts_apt_dependencies:
  - netbase
  - gcc
  - python3-dev
  - python3-distutils
