---
- name: "Skipping webmap install due to non-intel platform"
  debug:
    msg: "non-intel, skipping webmap install"
  when: ansible_architecture != "x86_64"

- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_architecture == "x86_64"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  when: ansible_architecture == "x86_64"

- name: "Configure webmap for {{ ansible_distribution }}"
  include_tasks: "configure-{{ ansible_distribution }}.yml"
  when: ansible_architecture == "x86_64"
