---
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set up webmap
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  tags: install_webmap

- name: Configure webmap
  include_tasks: "configure-{{ ansible_distribution }}.yml"
  tags: configure_webmap
