---
- name: "Copy {{ webmap_config_file }} to {{ webmap_config_location }}"
  copy:
    src: "{{ webmap_config_file }}"
    dest: "{{ webmap_config_location }}"
    mode: 0644

- name: "Copy {{ webmap_executable }} to {{ webmap_executable_location }}"
  copy:
    src: "{{ webmap_executable }}"
    dest: "{{ webmap_executable_location }}"
    mode: 0755
