---
- name: enable freetakserver_ui
  service:
    name: "{{ fts_ui_service_name }}"
    enabled: "{{ fts_ui_enabled }}"

- name: reload freetakserver_ui
  service:
    name: "{{ fts_ui_service_name }}"
    state: reloaded

- name: set freetakserver_ui state
  service:
    name: "{{ fts_ui_service_name }}"
    state: "{{ fts_ui_state }}"
