---
- name: enable videoserver
  service:
    name: "{{ videoserver_service_name }}"
    enabled: "{{ videoserver_enabled }}"

- name: reload videoserver
  service:
    name: "{{ videoserver_service_name }}"
    state: reloaded

- name: set videoserver state
  service:
    name: "{{ videoserver_service_name }}"
    state: "{{ videoserver_state }}"
