---
- name: Template FTSConfig.yaml config file
  template:
    src: FTSConfig.yaml.j2
    dest: "{{ fts_config_path }}"
    mode: 0644

- name: Print IPv4 information
  debug:
    msg: "FreeTAKServer IPv4: {{ fts_ipv4 }}"

- name: Update FreeTAKServer IPv4 addresses in FTSConfig.yaml
  replace:
    path: "{{ fts_config_path }}"
    regexp: "0.0.0.0"
    replace: "'{{ fts_ipv4 }}'"

- name: Change FirstStart to False in MainConfig.py
  lineinfile:
    path: "{{ fts_install_path }}/controllers/configuration/MainConfig.py"
    regexp: '(\s+)first_start = True'
    line: '\1first_start = False'
    backrefs: true

- name: Template unit file
  template:
    src: fts.service.j2
    dest: "{{ unit_files_location }}/{{ fts_service_name }}.service"
    mode: 0644

- name: enable freetakserver
  service:
    name: "{{ fts_service_name }}"
    enabled: "{{ fts_enabled }}"
    use: systemd

- name: set freetakserver state
  service:
    name: "{{ fts_service_name }}"
    state: "{{ fts_state }}"
    use: systemd
