---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include FTSConfig variables
  include_vars: "FTSConfig.yml"

- name: Get sitepackages directory
  script: getsitepackages.py
  register: sitepackage_dir

- name: Print sitepackages directory
  debug:
    msg: "{{ sitepackage_dir.stdout_lines }}"

- name: Setting sitepackages
  set_fact:
    fts_python_sitepackages: "{{ sitepackage_dir.stdout_lines }}"

- name: Print fts_python_sitepackages
  debug:
    msg: "{{ fts_python_sitepackages }}"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"
