---
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include FTSConfig variables
  include_vars: "FTSConfig.yml"

- name: Set up FreeTAKServer
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  tags: install_fts

- name: Configure FreeTAKServer
  include_tasks: "configure-{{ ansible_distribution }}.yml"
  tags: configure_fts
