---
- name: "Include {{ ansible_distribution }}-specific variables for"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include FTSConfig variables
  include_vars: "FTSConfig.yml"

- name: Uninstall
  include_tasks: "uninstall-{{ ansible_distribution }}.yml"
  when: uninstall_fts

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  when: not uninstall_fts
