---
- name: "Include OS-specific variables for {{ ansible_distribution }}"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "roles/freetakserver/vars/{{ ansible_distribution }}.yml"

- name: Include FTSConfig variables
  include_vars: "{{ item }}"
  with_first_found:
    - "FTSConfig.yml"
    - "roles/freetakserver/vars/FTSConfig.yml.yml"

- name: "Set up FreeTAKServer for {{ ansible_distribution }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}.yml"
    - "roles/freetakserver/tasks/setup-{{ ansible_distribution }}.yml"
  tags: install_fts

- name: "Configure FreeTAKServer for {{ ansible_distribution }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - "configure-{{ ansible_distribution }}.yml"
    - "roles/freetakserver/tasks/configure-{{ ansible_distribution }}.yml"
  tags: configure_fts
