---
- name: Install apt dependencies
  apt:
    name: "{{ fts_apt_dependencies | list }}"

- name: "Install {{ fts_pip_package_name }}"
  shell: "conda run -n {{ VENV_NAME }} pip install -y {{ fts_pip_package_name }}"
