---
- name: Install apt dependencies
  apt:
    name: "{{ fts_apt_dependencies }}"

- name: "Install {{ fts_pip_package_name }}"
  pip:
    name: "{{ fts_pip_package_name }}"
    executable: "pip{{ python3_version }}"
