---
videoserver_package_location: /tmp/rtsp-simple-server.tar.gz
videoserver_folder: /tmp/rtsp-simple-server
videoserver_config_location: /opt/rtsp-simple-server.yml
videoserver_executable_location: /usr/local/bin/rtsp-simple-server
