---
- name: Install apt dependencies
  apt:
    name: "{{ item }}"
  loop:
    - python3-dev
    - python3-setuptools
    - build-essential
    - python3-gevent
    - python3-lxml
    - libcairo2-dev
    - python3.8
    - python3-pip
  tags: FTS

- name: Remove previous FTS installations
  pip:
    name: FreeTAKServer
    state: absent
    executable: pip3
  tags: FTS

- name: Install pip pre install dependencies
  pip:
    name: pycairo
  tags: FTS

- name: Install FreeTAKServer python package
  pip:
    name: FreeTAKServer
    executable: pip3
  tags: FTS
