---
- name: Enable service fts, and not touch the state
  ansible.builtin.service:
    name: fts
    enabled: yes

- name: Start service fts, if not started
  ansible.builtin.service:
    name: fts
    state: started
