---
uninstall_nodered: false

# system information
noderedserver_ipv4: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0], true) }}"

nodered_service_name: nodered

# Set initial service state. Recommended values: `started` or `stopped`.
nodered_state: started

# Enable service.
nodered_enabled: true

nodered_dependencies:
  - npm

nodered_npm_packages:
  - node-red
  - node-red-admin

nodered_nodes:
  - node-red-contrib-config
  - node-red-dashboard

nodered_flows:
  - salute.json
  - videochecker.json
