---
# system information
fts_ip_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

# Set initial service state.
# Recommended values: `started` or `stopped`.
nodered_state: started

# Enable service.
nodered_enabled: true
