---
- name: Linux Playbook with Separation of Concern
  hosts: all
  become: true
  pre_tasks:
    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml

- hosts: freetakserver
  become: true
  roles:
    - freetakserver
    - freetakserver_ui
    - webmap
    - output

- hosts: videoserver
  become: true
  roles:
    - videoserver
    - output

- hosts: noderedserver
  become: true
  roles:
    - nodered
    - output
