---
- name: Linux Playbook with Separation of Concern
  hosts: all
  become: true
  pre_tasks:
    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml

  post_tasks:
    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

- hosts: freetakserver
  become: true
  roles:
    - freetakserver
    - freetakserver_ui
    - webmap

- hosts: videoserver
  become: true
  roles:
    - videoserver

- hosts: noderedserver
  become: true
  roles:
    - nodered
