---
- name: Linux Playbook with Separation of Concern
  hosts: all
  become: true
  pre_tasks:
    - name: Prevent handlers from running
      set_fact:
        run_handlers: false

    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml

    - name: Use systemctl replacement workaround
      get_url:
        url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py
        dest: /usr/local/bin/systemctl
        mode: 0755

- hosts: freetakserver
  become: true
  tasks:
    - name: Install FreeTAKServer
      include_role:
        name: freetakserver

    - name: Install FreeTAKServer-UI
      include_role:
        name: freetakserver_ui

    - name: Uninstall FreeTAKServer
      include_role:
        name: freetakserver
      vars:
        uninstall_fts: true

    - name: Uninstall FreeTAKServer-UI
      include_role:
        name: freetakserver_ui
      vars:
        uninstall_fts_ui: true

- hosts: webmapserver
  become: true
  tasks:
    - name: Install webmap
      include_role:
        name: webmap

    - name: Uninstall webmap
      include_role:
        name: webmap
      vars:
        uninstall_webmap: true

- hosts: videoserver
  become: true
  tasks:
    - name: Install videoserver
      include_role:
        name: videoserver

    - name: Uninstall videoserver
      include_role:
        name: videoserver
      vars:
        uninstall_videoserver: true

- hosts: noderedserver
  become: true
  tasks:
    - name: Install nodered
      include_role:
        name: nodered

    - name: Uninstall nodered
      include_role:
        name: nodered
      vars:
        uninstall_nodered: true
