---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: freetakserver
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: webmapserver
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: videoserver
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: noderedserver
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible

lint: |
  set -e
  yamllint .

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
