---
- name: reload webmap
  service:
    name: webmap
    state: reloaded

- name: enable webmap
  service:
    name: webmap
    enabled: "{{ webmap_enabled }}"

- name: set webmap state
  service:
    name: webmap
    state: "{{ webmap_state }}"
