---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  register: update
  retries: 5
  until: update is success

- name: Install python3 and python3-pip
  apt:
    name: "{{ item }}"
  loop:
    - python3
    - python3-pip
