---
- name: Print IPv4 information
  debug:
    msg: "Video Server IPv4: {{ videoserver_ipv4 }}"

- name: Template config file
  template:
    src: rtsp-simple-server.yml.j2
    dest: "{{ videoserver_config_location }}"
    mode: 0644

- name: Template unit file
  template:
    src: rtsp-simple-server.service.j2
    dest: "{{ unit_files_location }}/{{ videoserver_service_name }}.service"
    mode: 0644

- name: enable videoserver
  service:
    name: "{{ videoserver_service_name }}"
    enabled: "{{ videoserver_enabled }}"
    use: systemd

- name: set videoserver state
  service:
    name: "{{ videoserver_service_name }}"
    state: "{{ videoserver_state }}"
    use: systemd
