---
- name: Update api status in configuration
  replace:
    path: /tmp/rtsp-simple-server.yml
    regexp: 'api: no'
    replace: 'api: yes'

- name: Update api ip in configuration
  replace:
    path: /tmp/rtsp-simple-server.yml
    regexp: 'apiAddress: 127.0.0.1:9997'
    replace: "apiAddress: {{ hostvars.videoserverNode.ansible_host }}:9997"

- name: Update protocols in configuration
  replace:
    path: /tmp/rtsp-simple-server.yml
    regexp: 'protocols: [udp, multicast, tcp]'
    replace: 'protocols: [tcp]'

- name: move config file
  command: mv /tmp/rtsp-simple-server.yml /usr/local/etc/rtsp-simple-server.yml

- name: move server file
  command: mv /tmp/rtsp-simple-server /usr/local/bin/rtsp-simple-server

- name: Create video server service
  template: 
    src: 'rtsp-simple-server.service.j2' 
    dest: '/lib/systemd/system/rtsp-simple-server.service' 
    mode: 0644
  notify:
    - reload systemctl

- name: Enable service rtsp-simple-server, and not touch the state
  service:
    name: rtsp-simple-server
    enabled: yes
  become: true

- name: Start service rtsp-simple-server, if not started
  service:
    name: rtsp-simple-server
    state: started
  become: true
