---
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set up videoserver
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  tags: install_videoserver

- name: Configure videoserver
  include_tasks: "configure-{{ ansible_distribution }}.yml"
  tags: configure_videoserver
