---
- name: Include videoserver variables
  include_vars:
    file: main.yml
    name: vars

- name: Install rtsp-simple-server on machine
  import_tasks: installation.yml

- name: Configure rtsp-simple-server on machine
  import_tasks: configuration.yml
