---
- name: "Unarchive {{ videoserver_package }} to {{ videoserver_folder }}"
  unarchive:
    src: "{{ videoserver_package }}"
    dest: /tmp
    creates: "{{ videoserver_folder }}"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

- name: "Copy {{ videoserver_folder }}/{{ videoserver_executable }} to {{ videoserver_executable_location }}"
  copy:
    src: "{{ videoserver_folder }}/{{ videoserver_executable }}"
    dest: "{{ videoserver_executable_location }}"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    remote_src: true
    mode: 0755
