---
- name: Linux Playbook with One Instance
  hosts: instance
  become: true
  pre_tasks:
    - name: Use systemctl replacement workaround
      get_url:
        url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py
        dest: /usr/local/bin/systemctl
        mode: 0755
  roles:
    - freetakserver
    - freetakserver_ui
    - webmap
    - videoserver
    - nodered
