---
- name: Linux Playbook with One Instance
  hosts: instance
  vars:
    # Node-RED Server will wait for Video Server
    nodered_wait_for_videoserver: true
    # Max seconds Node-RED Server will wait
    nodered_wait_for_videoserver_timeout: 600
  become: true
  pre_tasks:
    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml

  post_tasks:
    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

  roles:
    - freetakserver
    - freetakserver_ui
    - webmap
    - videoserver
    - nodered
