---
- name: Linux Playbook with One Instance
  hosts: instance
  become: true
  pre_tasks:
    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml
  roles:
    - freetakserver
    - freetakserver_ui
    - webmap
    - videoserver
    - nodered
    - output
