---
- name: set superuser password
  command: murmurd -ini /etc/mumble-server.ini -supw "{{ murmur_superuser_password }}"
  failed_when: false

- name: print murmur ip
  debug:
    msg: "Murmur (Mumble Server) IP: {{ murmur_ipv4 }}:{{ murmur_port }}"

- name: print murmur credentials
  debug:
    msg: "username: SuperUser     password: {{ murmur_superuser_password }}"

- name: print reconfigure message
  debug:
    msg: "to reconfigure murmur (mumble server) enter: sudo dpkg-reconfigure mumble-server"
