---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install apt packages
  apt:
    name: "{{ python3_apt_packages }}"

- name: "Install pip packages"
  shell: "conda run -n {{ VENV_NAME }} pip install -y {{ item }}"
  loop: "{{ pip3_packages }}"
