---
- name: enable nodered
  service:
    name: "{{ nodered_service_name }}"
    enabled: "{{ nodered_enabled }}"

- name: reload nodered
  service:
    name: "{{ nodered_service_name }}"
    state: reloaded

- name: set nodered state
  service:
    name: "{{ nodered_service_name }}"
    state: "{{ nodered_state }}"
