---
- name: Print IPv4 information
  debug:
    msg: "Using: {{ fts_ip_address }} for {{ role_name }}"

- name: Template unit file
  template:
    src: nodered.service.j2
    dest: "{{ unit_files_location }}/{{ nodered_service_name }}.service"
    mode: 0644
  notify:
    - enable nodered
    - set nodered state
