---
- name: Ensure group "nodered" exists
  group:
    name: nodered
    state: present

- name: Ensure group "nodered" exists
  user:
    name: nodered
    group: nodered

- name: Template unit file
  template:
    src: nodered.service.j2
    dest: "{{ unit_files_location }}/{{ nodered_service_name }}.service"
    mode: 0644

- name: enable nodered
  service:
    name: "{{ nodered_service_name }}"
    enabled: "{{ nodered_enabled }}"
    use: systemd

- name: set nodered state
  service:
    name: "{{ nodered_service_name }}"
    state: "{{ nodered_state }}"
    use: systemd
