---
- name: Ensure group "nodered" exists
  group:
    name: nodered
    state: present

- name: Ensure group "nodered" exists
  user:
    name: nodered
    group: nodered

- name: Template unit file
  template:
    src: nodered.service.j2
    dest: "{{ unit_files_location }}/{{ nodered_service_name }}.service"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: 0644

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "node-red"

- name: Enable service
  service:
    name: "{{ nodered_service_name }}"
    enabled: true
    use: systemd
  register: enable_nodered_state
  retries: 5
  until: enable_nodered_state is success

- name: Set service state
  service:
    name: "{{ nodered_service_name }}"
    state: "restarted"
    use: systemd
  register: set_nodered_state
  retries: 5
  until: set_nodered_state is success

- name: Import Node-RED flows via HTTP POST
  uri:
    url: "http://{{ noderedserver_ipv4 }}:1880/flows"
    method: POST
    headers:
      Node-RED-API-Version: v1
    body: "{{ nodered_post_flows_body }}"
    body_format: json
    status_code: 204
