---
- name: Install NodeRed apt dependencies
  apt:
    name: "{{ item }}"
  loop:
    - nodejs
    - npm

- name: Install NodeRed with npm
  npm:
    name: node-red
    global: yes
    unsafe_perm: yes

- name: Create unit file for NodeRed
  template:
    src: nodered.service.j2
    dest: /lib/systemd/system/nodered.service
    mode: 0644
  notify:
    - reload systemctl

- name: Enable NodeRed service and not touch the state
  service:
    name: nodered
    enabled: yes
  become: true

- name: Start NodeRed service, if not started
  service:
    name: nodered
    state: started
  become: true
