---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "roles/nodered/vars/{{ ansible_distribution }}.yml"

- name: Set up Node-RED
  include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}.yml"
    - "roles/nodered/tasks/setup-{{ ansible_distribution }}.yml"
  tags: install_nodered

- name: Configure Node-RED
  include_tasks: "{{ item }}"
  with_first_found:
    - "configure-{{ ansible_distribution }}.yml"
    - "roles/nodered/tasks/configure-{{ ansible_distribution }}.yml"
  tags: configure_nodered
