---
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set up Node-RED
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  tags: install_nodered

- name: Configure Node-RED
  include_tasks: "configure-{{ ansible_distribution }}.yml"
  tags: configure_nodered
