---
- name: Wait for apt lock
  shell: >
    while fuser /var/lib/dpkg/lock >
    /dev/null 2>&1;
    do sleep 3; done;
  changed_when: false

- name: Install apt dependencies
  apt:
    name: "{{ nodered_dependencies }}"

- name: Install with npm
  npm:
    name: "{{ item }}"
    global: true
    unsafe_perm: true
  loop: "{{ nodered_npm_packages | list }}"
  register: nodered

- name: "Configure"
  include_tasks: "configure-{{ ansible_distribution }}.yml"
  when: nodered.changed
