---
- name: Install npm and nodejs
  apt:
    name: "{{ npm_apt_packages | list }}"
  ignore_errors: true

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: true
    unsafe_perm: true
  loop: "{{ nodered_npm_packages | list }}"

- name: Install Node-RED nodes with npm
  npm:
    name: "{{ item }}"
    path: "{{ nodered_install_folder }}"
  loop: "{{ nodered_nodes | list }}"

- name: Create flows directory
  file:
    path: "{{ nodered_install_folder }}/lib/flows"
    state: directory
    mode: 0755

- name: "Template backup Node-RED flows"
  template:
    src: "{{ item }}.j2"
    dest: "{{ nodered_install_folder }}/lib/flows/{{ item }}"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: 0644
  loop: "{{ nodered_flows }}"

- name: "Template flows.json to /tmp/flows.json"
  template:
    src: "flows.json.j2"
    dest: "/tmp/flows.json"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: 0644
