---
- name: Wait for apt lock
  shell: >
    while fuser /var/lib/dpkg/lock >
    /dev/null 2>&1;
    do sleep 3; done;
  changed_when: false

- name: Install npm
  apt:
    name: npm
  ignore_errors: true

- name: Execute script to install the NodeSource Node.js 17.x repo
  shell: curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
  args:
    warn: no

- name: Install nodejs
  apt:
    name: nodejs

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: true
    unsafe_perm: true
  loop: "{{ nodered_npm_packages | list }}"

- name: Install Node-RED nodes via npm
  npm:
    name: "{{ item }}"
    path: "{{ nodered_install_folder | default('/root/.node-red') }}"
  loop: "{{ nodered_nodes }}"

- name: Create flows directory
  ansible.builtin.file:
    path: "{{ nodered_install_folder | default('/root/.node-red') }}/lib/flows"
    state: directory
    mode: 0755

- name: "Template Node-RED flows to {{ nodered_install_folder }}/lib/flows"
  template:
    src: "{{ item }}.j2"
    dest: "{{ nodered_install_folder | default('/root/.node-red') }}/lib/flows/{{ item }}"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: 0755
  loop: "{{ nodered_flows }}"

- name: "Template flows.json to {{ nodered_install_folder }}"
  template:
    src: "flows.json.j2"
    dest: "{{ nodered_install_folder | default('/root/.node-red') }}"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: 0755
