---
- name: Wait for apt lock
  shell: >
    while fuser /var/lib/dpkg/lock >
    /dev/null 2>&1;
    do sleep 3; done;
  changed_when: false

- name: Install npm
  apt:
    name: npm
  ignore_errors: true

- name: Execute script to install the NodeSource Node.js 17.x repo
  shell: curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
  args:
    warn: no

- name: Install nodejs
  apt:
    name: nodejs

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: true
    unsafe_perm: true
  loop: "{{ nodered_npm_packages | list }}"

- name: "Copy Node-RED flows to {{ nodered_flows_location }}"
  copy:
    src: "{{ item }}"
    dest: "{{ nodered_flows_location | default('/root/.node-red') }}"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: 0755
  loop: "{{ nodered_flows }}"

- name: Import Node-RED flows via HTTP POST
  uri:
    url: "http://{{ noderedserver_ipv4 }}:1880/flows"
    method: POST
    body: "{{ lookup('file','{{ item }}') }}"
    status_code: 204
    body_format: json
  loop: "{{ nodered_flows }}"
