---
- name: Wait for apt lock
  shell: >
    while fuser /var/lib/dpkg/lock >
    /dev/null 2>&1;
    do sleep 3; done;

- name: Install Node-RED apt dependencies
  apt:
    name: "{{ nodered_dependencies }}"

- name: Install Node-RED with npm
  npm:
    name: node-red
    global: true
    unsafe_perm: true
