---
- name: Stop service
  service:
    name: "{{ nodered_service_name }}"
    state: stopped
  ignore_errors: true

- name: Remove unit file
  file:
    path: "{{ unit_files_location }}/{{ nodered_service_name }}.service"
    state: absent

- name: Uninstall
  npm:
    name: node-red
    state: absent
    global: true
    unsafe_perm: true
