---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: freetakserver
    image: mcr.microsoft.com/windows
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: webmap
    image: mcr.microsoft.com/windows
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: videoserver
    image: mcr.microsoft.com/windows
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: noderedserve
    image: mcr.microsoft.com/windows
    privileged: true
    pre_build_image: true
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .

scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    # - syntax
    - create
    - converge
    # - idempotence
    - verify
    - destroy
