---
uninstall_videoserver: false

videoserver_api_url: https://api.github.com/repos/aler9/rtsp-simple-server/releases/latest

# system information
videoserver_ip_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0], true) }}"

videoserver_executable: rtsp-simple-server
videoserver_config_file: rtsp-simple-server.yml
videoserver_service_name: rtsp-simple-server

# Set initial service state. Recommended values: `started` or `stopped`.
videoserver_state: started

# Enable service.
videoserver_enabled: true
