---
fts_ui_sqlachemy_db_uri: /opt/FTSServer-UI.db

my_sitepackages: "{{ CONDA_PREFIX }}/lib/python3.8/site-packages"

fts_ui_install_path: "{{ my_sitepackages }}/FreeTAKServer-UI"

fts_ui_apt_packages:
  - python3-distutils

fts_ui_pip_packages:
  - pyyaml
