---
# Example playbook to install all FreeTAKServer and components
- name: Ubuntu 20.04 Playbook with One Instance
  hosts: all
  become: true
  roles:
    - common
    - python3
    - freetakserver
    - freetakserver_ui
    - webmap
    - videoserver
    - nodered
