---
- name: Edit config so ip is correct
  replace:
    path: '{{ fts_ui_installation_path }}/config.py'
    regexp: '127.0.0.1'
    replace: "{{ hostvars.mainNode.ansible_host | default(ansible_default_ipv4.address) }}"

- name: Edit config so ip is correct
  replace:
    path: '{{ fts_ui_installation_path }}/config.py'
    regexp: 'WEBMAPIP = "127.0.0.1"'
    replace: "WEBMAPIP = \"{{ hostvars.webmapNode.ansible_host | default(ansible_default_ipv4.address) }}\""

- name: create unit file for FTS
  template:
    src: 'fts-ui.service.j2'
    dest: '/lib/systemd/system/fts-ui.service'
    mode: 0644
  notify:
    - reload systemctl

- name: Enable service fts-ui, and not touch the state
  service:
    name: fts-ui
    enabled: yes
  become: true

- name: Start service fts-ui, if not started
  service:
    name: fts-ui
    state: started
  become: true
