- name: Edit config so ip is correct
  ansible.builtin.lineinfile:
    path: /usr/local/lib/python3.8/dist-packages/FreeTAKServer-UI/config.py
    regexp: '127.0.0.1'
    line: "'{{ hostvars['mainNode'].ansible_host }}'"
    backrefs: yes

- name: create unit file for FTS
  template: src='fts-ui.service.j2' dest='/lib/systemd/system/fts-ui.service' mode=644
  notify:
    - reload systemctl

- name: Enable service fts-ui, and not touch the state
  ansible.builtin.service:
    name: fts-ui
    enabled: yes
  become: true

- name: Start service fts-ui, if not started
  ansible.builtin.service:
    name: fts-ui
    state: started
  become: true