---
name: CI

'on':
  pull_request:
  push:
    branches:
      - master
      - 'develop/**'
  schedule:
    - cron: "0 5 * * 0"

jobs:
  molecule:
    name: Molecule Tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distros:
          - ubuntu2004

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip install ansible molecule[docker,lint] docker

      - name: Run Molecule tests --scenario-name default
        run: ANSIBLE_VERBOSITY=2 molecule test
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Run Molecule tests --scenario-name multiple_machines
        run: ANSIBLE_VERBOSITY=2 molecule test
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
